language: perl
perl:
  - "5.14" 
  - "5.20"              # installs latest perl 5.20 (if not already available)
  - "dev"               # installs latest developer release of perl (e.g. 5.21.8)
  - "blead"             # builds perl from git
matrix:
  allow_failures:
    - perl: blead       # ignore failures for blead perl
sudo: false             # faster builds as long as you don't need sudo access
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  irc: "irc://irc.perl.org/#perlrdf"

